name: plot_web_app
description: "This is a flutter project for Plot Web"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  graphview: ^1.2.0
  sqflite: ^2.3.2
  flutter_multiselect: ^1.0.0

  english_words: ^4.0.0
  provider: ^6.0.0
  path: ^1.9.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/favicon.png"